### ISSUE TITLE
Error in OF_SRProtocol.cc

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/SDN4CoRE#1]
Hi, 

I got the following errors in OF_SRProtocol.cc: 

`sdn4core/switch/avb/services/avb/SRP/OF_SRProtocol.cc:54:68: error: no member named 'priortyAndRankSRClassA' in 'SDN4CoRE::OF_SRProtocol'`

`sdn4core/switch/avb/services/avb/SRP/OF_SRProtocol.cc:58:73: error: no member named 'priortyAndRankSRClassB' in 'SDN4CoRE::OF_SRProtocol'`

**Comment by SaloM0nk** [comment]
Hi franc444,
I have not seen this build error before and cannot reproduce it with the currently released Version. Please refresh all your repositories and check if you have the most recent versions of CoRE4INET, OpenFlow (our fork) and SDN4CoRE. 
If the error persists please provide some more Information on your OS and which OMNeT++ Version and INET Version you are running.
Best regards,
Timo

**Comment by franc444** [comment]
Thanks Timo, the error is gone after I refreshed all repositories.
