### ISSUE TITLE
SDN4CoRE and  FiCo4OMNeT

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/SDN4CoRE#3]
Hi, 

Can SDN4CoRE work with [FiCo4OMNeT](https://github.com/CoRE-RG/FiCo4OMNeT)? 

Thanks,

**Comment by SaloM0nk** [comment]
Hi,
for now, SDN4CoRE concentrates on combining Software-Defined Networking with real-time Ethernet technologies. 
Currently, no extensions are planned for the management of fieldbuses.
You can integrate, e.g., CAN communication with Ether-Networks using our SignalsAndGateways Framework.
Kind regards,
Timo

**Comment by franc444** [comment]
Thank you,
