### ISSUE TITLE
Qbv support

### ISSUE THREAD

**Issue by royarm** [CoRE-RG/SDN4CoRE#4]
Hello is it possible in your simulation to have tsn switches which support qbv with 8 priority  queues?
And can we add lldp messages to network for network discovery?

**Comment by SaloM0nk** [comment]
Hello,
yes, it is indeed possible to use 802.1Qbv. Under "src/sdn4core/switch/" there are several implementations for switches using 802.1Qbv. I recommend using the TSNOpenFlowSwitch or TSNOFNCSwitch if you want to use NETCONF applications as well. 

If you want to use OpenFlow to carry out the LLDP you should be able to use the LLDP controller application implemented in the [OpenFlow framework](https://github.com/CoRE-RG/OpenFlow/tree/master/src/openflow/controllerApps) (see "OpenFlow/src/openflow/controllerApps/LLDPAgent") which should work in SDN4CoRE.
If you try it, I would be glad for your feedback if the OpenFlow LLDP works as expected with TSN switches.

Best Regards 
Timo
